services:
  mysql:
    container_name: go-bookstore
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - bookstore-net
    restart: unless-stopped

networks:
  bookstore-net:
    driver: bridge

volumes:
  mysql_data:
